"""Add video conferencing and scheduling features

Revision ID: 933c4c27cc48
Revises: a97bb5e15df6
Create Date: 2025-09-25 21:56:05.334651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933c4c27cc48'
down_revision = 'a97bb5e15df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('connection_quality', sa.String(length=20), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('video_enabled', sa.Boolean(), nullable=True),
    sa.Column('audio_enabled', sa.Boolean(), nullable=True),
    sa.Column('screen_sharing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('patient_consent', sa.Boolean(), nullable=True),
    sa.Column('therapist_consent', sa.Boolean(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('reminder_type', sa.String(length=30), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('join_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('meeting_password', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_patient', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_therapist', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['room_id'])
        batch_op.create_foreign_key(None, 'user', ['cancelled_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancelled_by')
        batch_op.drop_column('reminder_sent_therapist')
        batch_op.drop_column('reminder_sent_patient')
        batch_op.drop_column('timezone')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('meeting_password')
        batch_op.drop_column('join_url')
        batch_op.drop_column('room_id')
        batch_op.drop_column('actual_duration')

    op.drop_table('session_reminder')
    op.drop_table('session_recording')
    op.drop_table('session_participant')
    op.drop_table('session_message')
    # ### end Alembic commands ###
