#!/bin/bash

# Script to replace all Heroicons with Lucide React icons

echo "Starting icon replacement..."

# Common icon mappings
declare -A icon_map=(
    ["Bars3Icon"]="Menu"
    ["XMarkIcon"]="X"
    ["UserIcon"]="User"
    ["UserCircleIcon"]="UserCircle"
    ["UserGroupIcon"]="Users"
    ["Cog6ToothIcon"]="Settings"
    ["HomeIcon"]="Home"
    ["CalendarIcon"]="Calendar"
    ["ChatBubbleLeftRightIcon"]="MessageCircle"
    ["BuildingOfficeIcon"]="Building"
    ["DocumentTextIcon"]="FileText"
    ["BookOpenIcon"]="BookOpen"
    ["ChevronDownIcon"]="ChevronDown"
    ["ArrowRightOnRectangleIcon"]="LogOut"
    ["BellIcon"]="Bell"
    ["SunIcon"]="Sun"
    ["MoonIcon"]="Moon"
    ["LanguageIcon"]="Languages"
    ["PaintBrushIcon"]="Palette"
    ["ComputerDesktopIcon"]="Monitor"
    ["EyeIcon"]="Eye"
    ["EyeSlashIcon"]="EyeOff"
    ["ExclamationTriangleIcon"]="AlertTriangle"
    ["HeartIcon"]="Heart"
    ["StarIcon"]="Star"
    ["MagnifyingGlassIcon"]="Search"
    ["FunnelIcon"]="Filter"
    ["DocumentIcon"]="File"
    ["PhotoIcon"]="Image"
    ["PlusIcon"]="Plus"
    ["TrashIcon"]="Trash2"
    ["PencilIcon"]="Edit"
    ["CheckIcon"]="Check"
    ["WifiIcon"]="Wifi"
    ["PlayIcon"]="Play"
    ["PauseIcon"]="Pause"
    ["StopIcon"]="Square"
    ["SpeakerWaveIcon"]="Volume2"
    ["SpeakerXMarkIcon"]="VolumeX"
    ["VideoCameraIcon"]="Video"
    ["VideoCameraSlashIcon"]="VideoOff"
    ["MicrophoneIcon"]="Mic"
    ["MicrophoneSlashIcon"]="MicOff"
    ["PhoneIcon"]="Phone"
    ["PhoneXMarkIcon"]="PhoneOff"
    ["ShareIcon"]="Share"
    ["ClockIcon"]="Clock"
    ["MapPinIcon"]="MapPin"
    ["EnvelopeIcon"]="Mail"
    ["ChartBarIcon"]="BarChart"
    ["InformationCircleIcon"]="Info"
    ["ExclamationCircleIcon"]="AlertCircle"
    ["CheckCircleIcon"]="CheckCircle"
    ["ShieldCheckIcon"]="ShieldCheck"
    ["ShieldExclamationIcon"]="ShieldAlert"
    ["LockClosedIcon"]="Lock"
    ["EllipsisVerticalIcon"]="MoreVertical"
    ["EllipsisHorizontalIcon"]="MoreHorizontal"
    ["ArrowPathIcon"]="RotateCw"
    ["ArrowDownTrayIcon"]="Download"
    ["ArrowUpTrayIcon"]="Upload"
    ["PaperClipIcon"]="Paperclip"
    ["LinkIcon"]="Link"
    ["GlobeAltIcon"]="Globe"
    ["CloudIcon"]="Cloud"
    ["ServerIcon"]="Server"
    ["CpuChipIcon"]="Cpu"
    ["SignalIcon"]="Signal"
    ["BoltIcon"]="Zap"
    ["FireIcon"]="Flame"
    ["AcademicCapIcon"]="GraduationCap"
    ["BeakerIcon"]="Flask"
    ["CalculatorIcon"]="Calculator"
    ["CameraIcon"]="Camera"
    ["ChatBubbleOvalLeftEllipsisIcon"]="MessageSquare"
    ["ClipboardIcon"]="Clipboard"
    ["CodeBracketIcon"]="Code"
    ["CogIcon"]="Settings"
    ["CommandLineIcon"]="Terminal"
    ["CreditCardIcon"]="CreditCard"
    ["CubeIcon"]="Box"
    ["CurrencyDollarIcon"]="DollarSign"
    ["DevicePhoneMobileIcon"]="Smartphone"
    ["DeviceTabletIcon"]="Tablet"
    ["FaceSmileIcon"]="Smile"
    ["FaceFrownIcon"]="Frown"
    ["FlagIcon"]="Flag"
    ["FolderIcon"]="Folder"
    ["FolderOpenIcon"]="FolderOpen"
    ["GiftIcon"]="Gift"
    ["HandRaisedIcon"]="Hand"
    ["HashtagIcon"]="Hash"
    ["IdentificationIcon"]="CreditCard"
    ["InboxIcon"]="Inbox"
    ["KeyIcon"]="Key"
    ["LifebuoyIcon"]="LifeBuoy"
    ["LightBulbIcon"]="Lightbulb"
    ["MegaphoneIcon"]="Megaphone"
    ["NewspaperIcon"]="Newspaper"
    ["NoSymbolIcon"]="Ban"
    ["PaintBrushIcon"]="Palette"
    ["PaperAirplaneIcon"]="Send"
    ["PrinterIcon"]="Printer"
    ["QrCodeIcon"]="QrCode"
    ["QuestionMarkCircleIcon"]="HelpCircle"
    ["RocketLaunchIcon"]="Rocket"
    ["ScaleIcon"]="Scale"
    ["ScissorsIcon"]="Scissors"
    ["ShoppingBagIcon"]="ShoppingBag"
    ["ShoppingCartIcon"]="ShoppingCart"
    ["SparklesIcon"]="Sparkles"
    ["Square2StackIcon"]="Copy"
    ["Square3Stack3DIcon"]="Layers"
    ["TagIcon"]="Tag"
    ["TicketIcon"]="Ticket"
    ["TrophyIcon"]="Trophy"
    ["TruckIcon"]="Truck"
    ["TvIcon"]="Tv"
    ["UserPlusIcon"]="UserPlus"
    ["WrenchScrewdriverIcon"]="Wrench"
)

# Find all files that still use heroicons
find src -name "*.jsx" -type f | while read file; do
    if grep -q "@heroicons/react" "$file"; then
        echo "Processing: $file"
        
        # Replace the import statement
        sed -i 's/@heroicons\/react\/24\/outline/lucide-react/g' "$file"
        sed -i 's/@heroicons\/react\/24\/solid/lucide-react/g' "$file"
        
        # Replace individual icon names
        for heroicon in "${!icon_map[@]}"; do
            lucide_icon="${icon_map[$heroicon]}"
            # Replace in import statements
            sed -i "s/${heroicon}/${lucide_icon}/g" "$file"
        done
        
        # Handle special cases for solid icons
        sed -i 's/HeartIconSolid/Heart/g' "$file"
        sed -i 's/StarIconSolid/Star/g' "$file"
        
        echo "Updated: $file"
    fi
done

echo "Icon replacement complete!"
echo "Please review the changes and test your application."
